### ISSUE TITLE
let's play with Strings and Texts in python

### ISSUE THREAD

**Issue by arjuntony** [asarfraaz/share2learn#10]
1.Strings operations
2.examples 
3.Significance of Strings in IT Networking

**Comment by asarfraaz** [comment]
A gentle reminder to start writing your blog post. 

Target to atleast have the first draft ready by Thursday, 
so that you can allocate 2 days for the review
and be ready to publish it on Saturday.

**Comment by arjuntony** [comment]
Hi @asarfraaz, As Discussed with you,  My Publish date is Tuesday. I will have the post ready by Saturday.

**Comment by arjuntony** [comment]
merged with master
