### ISSUE TITLE
Normalisation and Standardisation

### ISSUE THREAD

**Issue by asarfraaz** [asarfraaz/share2learn#7]
1. Meaning
2. when to use
3. where to use
4. usecase

**Comment by asarfraaz** [comment]
Manjunath to assign this to himself

**Comment by Manju410** [comment]
> Manjunath to assign this to himself

Done sir.

**Comment by asarfraaz** [comment]
All the Best

**Comment by asarfraaz** [comment]
Fixed with Pull Request #15
